location: .gitman
sources:
  - name: uvdar_leader_follower
    type: git
    repo: https://github.com/ctu-mrs/uvdar_leader_follower.git
    sparse_paths:
      -
    rev: master
    link: ros_packages/uvdar_leader_follower
  - name: uvdar_core
    type: git
    repo: https://github.com/ctu-mrs/uvdar_core.git
    sparse_paths:
      -
    rev: d6c7edb3a36909cdbc87b45231b6f8360302936e
    link: ros_packages/uvdar_core
  - name: uvdar_gazebo_plugin
    type: git
    repo: https://github.com/ctu-mrs/uvdar_gazebo_plugin.git
    sparse_paths:
      -
    rev: a1546bf67d5c075844e81173518e058cd48185d3
    link: ros_packages/uvdar_gazebo_plugin
  - name: summer_school_supervisor
    type: git
    repo: https://github.com/ctu-mrs/summer_school_supervisor.git
    sparse_paths:
      -
    rev: master
    link: ros_packages/summer_school_supervisor
  - name: trajectory_loader
    type: git
    repo: https://github.com/ctu-mrs/trajectory_loader.git
    sparse_paths:
      -
    rev: master
    link: ros_packages/trajectory_loader
